name: Journey
on: [push, pull_request]
jobs:
  ci:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: "lint"
        run: dart analyze .
      - name: "test"
        run: flutter test
